# configs/hand_manipulation_config.yaml
env:
  hand_model_path: "models/dex_hand/scene_left.xml"
  control_timestep: 0.002
  episode_duration: 2.0 # seconds

object:
  name: "cube_body"
  joint_name: "cube_joint"
  geom_size: [0.03, 0.03, 0.03]
  mass: 0.1
  initial_pos_relative: [0.0, 0.0, 0.05] # Relative to world origin, on top of table
  pos_randomization_range:
    x: [-0.02, 0.02]
    y: [-0.02, 0.02]
    z: [-0.005, 0.005] # Small up/down variation

rewards:
  object_height_factor: 100
  target_height: 0.15
  target_height_bonus: 500
  drop_penalty: 200

rl:
  total_timesteps: 50000 # Keep low for initial test, increase to millions for actual training
  log_dir: "./sac_hand_manipulation_logs/"
  model_save_path: "./trained_models/hand_policy.zip"
  learning_rate: 0.0003
  buffer_size: 10000
  learning_starts: 100 # Start learning quickly for test
  train_freq: [1, "episode"]
  gradient_steps: 1
  ent_coef: "auto"
  save_freq: 5000 # How often to save checkpoints during training