# configs/hand_manipulation_config.yaml
env:
  hand_model_path: "models/dex_hand/scene.xml"
  control_timestep: 0.002
  episode_duration: 8.0 # seconds

object:
  name: "cube"           # Changed from "ball_body" to "ball"
  joint_name: "cube_joint"     # Changed from "ball_joint" to "ball" (default name for freejoint)
  geom_name: "cube_geom"   # This already matches, no change needed
  size: [0.03, 0.04, 0.02] # Changed from "radius" to "size" and updated values for ellipsoid
  pos_randomization_range:
    x: [-0.02, 0.02]
    y: [-0.02, 0.02]
    z: [-0.005, 0.005]
  initial_pos_relative: [0.3, 0.0, 0.1] # Changed from [0.3, 0.0, 0.0] to [0.3, 0.0, 0.1]

rewards:
  # Parameters for finger_proximity_reward
  distance_scale: 25.0
  distance_reward_factor: 8.0

  # Parameters for hand_z_position_reward
  hand_target_z: 0.03
  hand_z_reward_factor: 200.0

  # Parameters for object_y_position_reward
  target_y_position: 0.2
  y_pos_distance_scale: 20.0
  y_pos_reward_factor: 15.0

  # Parameters for hand_movement_reward (exploration)
  hand_joint_velocity_scaling: 0.05

rl:
  total_timesteps: 50000 # Keep low for initial test, increase to millions for actual training
  log_dir: "./sac_hand_manipulation_logs/"
  model_save_path: "./trained_models/hand_policy.zip"
  learning_rate: 0.0003
  buffer_size: 10000
  learning_starts: 100 # Start learning quickly for test
  train_freq: [1, "episode"]
  gradient_steps: 1
  ent_coef: "auto"
  save_freq: 5000 # How often to save checkpoints during training