# configs/hand_manipulation_config.yaml
env:
  hand_model_path: "models/dex_hand/scene.xml"
  control_timestep: 0.002
  episode_duration: 2.0 # seconds

object:
  name: "cube"           # Changed from "ball_body" to "ball"
  joint_name: "cube_joint"     # Changed from "ball_joint" to "ball" (default name for freejoint)
  geom_name: "cube_geom"   # This already matches, no change needed
  size: [0.03, 0.04, 0.02] # Changed from "radius" to "size" and updated values for ellipsoid
  pos_randomization_range:
    x: [-0.02, 0.02]
    y: [-0.02, 0.02]
    z: [-0.005, 0.005]

rewards:
  object_height_factor: 100
  target_height: 0.15
  target_height_bonus: 500
  drop_penalty: 200

rl:
  total_timesteps: 50000 # Keep low for initial test, increase to millions for actual training
  log_dir: "./sac_hand_manipulation_logs/"
  model_save_path: "./trained_models/hand_policy.zip"
  learning_rate: 0.0003
  buffer_size: 10000
  learning_starts: 100 # Start learning quickly for test
  train_freq: [1, "episode"]
  gradient_steps: 1
  ent_coef: "auto"
  save_freq: 5000 # How often to save checkpoints during training